apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: alerting
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      slack_api_url: 'https://hooks.slack.com/services/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'
    route:
      receiver: slack-notifications
    receivers:
      - name: slack-notifications
        slack_configs:
          - send_resolved: true
            channel: '#alerts'
            title: "{{ template \"slack.common.title\" . }}"
            text: "{{ template \"slack.common.text\" . }}"

